### PR TITLE
Change build system

### PR DESCRIPTION
**Pull request by 4re**
This is easier to maintain and works pretty well.

I did try to update travis.yml but I'm not sure the changes I did are sufficient.

### CODE REVIEW

**Comment by 4re** [comment]
I guess trusty is just too old.

**Comment by Khanattila** [comment]
Yes definitely.

**Comment by Khanattila** [comment]
But you can give it a try using ninja.

**Comment by 4re** [comment]
Yeah, I saw that, and about ninja, the thing is it is only a dumb tool like make, you usually use a smart and cool thing like `autotools` (mature but with a horrible syntax) or `meson` to do the job.

**Comment by 4re** [comment]
Reopening it to see if Travis lets me install meson one way or another.

**Comment by 4re** [comment]
OK, I guess somehow I managed :(

**Comment by Khanattila** [comment]
Thanks for your effort @4re. 
I will review it as soon as possible.

**Pull request merged**
